vims/src/vims/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = patterns('',
#    (r'^$', 'vims.virtualstore.views.openid.openid_start'),
#    (r'^finishOpenId/$', 'vims.virtualstore.views.openid.openid_finish'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'shared/login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/accounts/login/'}),
    url(r'^', include('virtualstore.urls')),
    url(r'^vims/', include('virtualstore.urls')),
    url(r'^(vims/)*', include('virtualstore.urls')),

    # url(r'^vims/', include('vims.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

vims/src/virtualstore/urls.py

from django.conf.urls import patterns, url
from vims import settings
from virtualstore.views import company, game, store, currency, category, \
    item, export, custom_attribute, resource


urlpatterns = patterns('virtualstore.views',
    url(r'^$',  company.list ),
    url(r'^company/add/$',  company.add ),
    url(r'^company/list/$',  company.list ),
    url(r'^company/edit/$',  company.edit ),
    url(r'^company/delete/$',  company.delete ),
    url(r'^game/add/$',  game.add ),
    url(r'^game/list/$',  game.list ),
    url(r'^game/edit/$',  game.edit ),
    url(r'^game/delete/$',  game.delete ),
    url(r'^store/add/$',  store.add ),
    url(r'^store/list/$',  store.list ),
    url(r'^store/edit/$',  store.edit ),
    url(r'^store/push/$',  store.push ),
    url(r'^store/delete/$',  store.delete ),
    url(r'^category/add/$',  category.add ),
    url(r'^category/list/$',  category.list ),
    url(r'^category/edit/$',  category.edit ),
    url(r'^category/delete/$',  category.delete ),
    url(r'^item/add/$',  item.add ),
    url(r'^item/list/$',  item.list ),
    url(r'^item/edit/$',  item.edit ),
    url(r'^item/delete/$',  item.delete ),
    url(r'^currency/add/$',  currency.add ),
    url(r'^currency/list/$',  currency.list ),
    url(r'^currency/edit/$',  currency.edit ),
    url(r'^custom_attribute/add/$',  custom_attribute.add ),
    url(r'^custom_attribute/list/$',  custom_attribute.list ),
    url(r'^custom_attribute/edit/$',  custom_attribute.edit ),
    url(r'^custom_attribute/delete/$',  custom_attribute.delete ),
    url(r'^resource/add/$',  resource.add ),
    url(r'^resource/list/$',  resource.list ),
    url(r'^resource/delete/$',  resource.delete ),    
    url(r'^export/json/$',  export.json ),
    url(r'^export/xml/$',  export.xml ),
    url(r'^export/resource/$',  export.resource ),
)

urlpatterns += patterns('',
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'shared/login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/accounts/login/'}),
    url(r'^content/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_DIR}),
)

vims/src/virtualstore/models.py
from django.db import models
from virtualstore.common import constants

# Create your models here.

class Company(models.Model):
    
    id = models.CharField(db_column ='company_id',
                          max_length=32, 
                          primary_key=True, 
                          unique=True, 
                          null=False, 
                          blank=False)
    
    name = models.CharField(max_length=255,
                            unique = True,
                            null = False,
                            blank = False)
    
    created_datetime = models.DateTimeField(auto_now_add=True, 
                                            editable=False, 
                                            null=False, 
                                            blank=False)
    
    created_by = models.IntegerField(max_length=11, 
                                     null=False, 
                                     blank=False)
    
    modified_datetime = models.DateTimeField(auto_now=True,
                                             editable=False, 
                                             null=False, 
                                             blank=True)
    
    modified_by = models.IntegerField(max_length=11, 
                                      null=False, 
                                      blank=True)
    
    def __unicode__(self):
        return u'%s : %s' % (self.id, self.name)

    class Meta:
        db_table = 'company'
        
class Game(models.Model):
    id = models.CharField(db_column ='game_id',
                          max_length=32, 
                          primary_key=True,
                          null=False, 
                          blank=False)
    
    company = models.ForeignKey(Company)
    
    name = models.CharField(max_length=100,
                            unique=True,
                            null=False,
                            blank=False)
    
    visible_id = models.IntegerField(max_length=11,
                                  null=False,
                                  blank=False)
    
    is_active = models.BooleanField(default=True,
                                    null=False)
    
    web_service_url = models.URLField(max_length=1000,
                                      null=False,
                                      blank=False)
    
    item_store_url = models.URLField(max_length=1000,
                                      null=False,
                                      blank=False)
    
    created_datetime = models.DateTimeField(auto_now_add=True, 
                                            editable=False, 
                                            null=False, 
                                            blank=False)
    
    created_by = models.IntegerField(max_length=11, 
                                     null=False, 
                                     blank=False)
    
    modified_datetime = models.DateTimeField(auto_now=True,
                                             editable=False, 
                                             null=False, 
                                             blank=True)
    
    modified_by = models.IntegerField(max_length=11, 
                                      null=False, 
                                      blank=True)
    
    def __unicode__(self):
        return u'%s - %s' % (self.name, self.company.name)
    
    class Meta:
        db_table = 'game'
        unique_together = (('company', 'name'),
                           ('company', 'visible_id'))

class CustomAttribute(models.Model):
    id          = models.AutoField(primary_key=True, db_column="custom_attribute_id")
    game        = models.ForeignKey(Game)
    name        = models.CharField(max_length=100)
    type        = models.CharField(max_length=50,choices=constants.CUSTOM_ATTRIBUTE_TYPES)
    mapped_column = models.CharField(max_length=13)
    type_meta_data = models.CharField(max_length=500, blank=True, null=True)

    created_datetime = models.DateTimeField(auto_now_add=True, 
                                            editable=False, 
                                            null=False, 
                                            blank=False)
    
    created_by = models.IntegerField(max_length=11, 
                                     null=False, 
                                     blank=False)
    
    modified_datetime = models.DateTimeField(auto_now=True,
                                             editable=False, 
                                             null=False, 
                                             blank=True)
    
    modified_by = models.IntegerField(max_length=11, 
                                      null=False, 
                                      blank=True)
    
    class Meta:
        db_table = 'custom_attribute'
        unique_together = ('game', 'name')        

class Store(models.Model):
    id = models.AutoField(db_column='store_id', 
                          primary_key=True, 
                          max_length=11)
    
    game = models.ForeignKey(Game)
    
    name = models.CharField(max_length=100,
                            null=False,
                            blank=False)
    
    visible_id = models.IntegerField(max_length=11,
                                  null=False,
                                  blank=False)
    
    is_active = models.BooleanField(default=True,
                                    null=False)
    
    position    = models.IntegerField(null=False, 
                                      blank=False)
                                      
    min_version  = models.CharField(max_length=50, 
                                    null=False, 
                                    default='1.0')
    
    max_version  = models.CharField(max_length=50, 
                                    null=True, 
                                    blank=True)
    
    category_attributes = models.ManyToManyField(CustomAttribute, 
                                                 related_name="category_attributes_set", 
                                                 db_table='category_attributes', 
                                                 blank=True)
    
    item_attributes = models.ManyToManyField(CustomAttribute, 
                                                 related_name="item_attributes_set", 
                                                 db_table='item_attributes', 
                                                 blank=True)
    
    created_datetime = models.DateTimeField(auto_now_add=True, 
                                            editable=False, 
                                            null=False, 
                                            blank=False)
    
    created_by = models.IntegerField(max_length=11, 
                                     null=False, 
                                     blank=False)
    
    modified_datetime = models.DateTimeField(auto_now=True,
                                             editable=False, 
                                             null=False, 
                                             blank=True)
    
    modified_by = models.IntegerField(max_length=11, 
                                      null=False, 
                                      blank=True)
    
    version     = models.IntegerField(blank=True, default=1)
    
    def __unicode__(self):
        return u'%s - %s' % (self.name, self.company.name)
    
    class Meta:
        db_table = 'store'
        unique_together = (('game', 'name'),
                           ('game', 'visible_id'))

class Category(models.Model):

    id          = models.AutoField(primary_key=True, 
                                   db_column='category_id')
    
    store       = models.ForeignKey(Store)
    
    name        = models.CharField(max_length = 100)
    
    description = models.CharField(max_length = 500,
                                   blank=True)
    
    visible_id = models.IntegerField(max_length=11,
                                       null=False,
                                       blank=False)
    
    position = models.IntegerField(null=False, 
                                   blank=False)    
    
    is_active = models.BooleanField(default=True,
                                    null=False)
    
    
    is_local = models.BooleanField(null=False, 
                                   default=True)
    
    is_new = models.BooleanField(null=False, 
                                 default=True)
    
    min_version  = models.CharField(max_length=50, 
                                    null=False, 
                                    default='1.0')
    
    max_version  = models.CharField(max_length=50, 
                                    null=True, 
                                    blank=True)
    
    visible_to   = models.CharField(max_length=10, 
                                    choices=constants.ENTITY_VISIBILITY_OPTIONS, 
                                    null=False, 
                                    default='dev')
    
    active_campaign = models.CharField(max_length=100, 
                                     default='default',
                                     editable=False)
    
    buy_price    = models.TextField(blank=True)
    
    sell_price    = models.TextField(blank=True)

    attribute_1    = models.CharField(max_length=constants.CUSTOM_ATTRIBUTE_SIZE, null=True, blank=True)
    attribute_2    = models.CharField(max_length=constants.CUSTOM_ATTRIBUTE_SIZE, null=True, blank=True)
    attribute_3    = models.CharField(max_length=constants.CUSTOM_ATTRIBUTE_SIZE, null=True, blank=True)
    attribute_4    = models.CharField(max_length=constants.CUSTOM_ATTRIBUTE_SIZE, null=True, blank=True)
    attribute_5    = models.CharField(max_length=constants.CUSTOM_ATTRIBUTE_SIZE, null=True, blank=True)

vims/src/virtualstore/views/export.py
from virtualstore.common import http_util, util
from virtualstore.services import resource_download_url, cache
from virtualstore.models import StoreCache
import binascii

def json(request):    
    store_id  = request.REQUEST.get('store_id')
    json_content = None
    zipped_json_binary = None
    
    store_cache_list = StoreCache.objects.filter(id=store_id)
    
    if len(store_cache_list) == 0:
        cache_obj = cache.update_store_cache(store_id)
    else:
        cache_obj = store_cache_list[0]
        
    json_content = cache_obj.json_data
    zipped_json_binary = binascii.unhexlify(cache_obj.json_binary_data)
    store_cache_list = None
    cache_obj = None
    
    if request.GET.get('zip', False) == 'true':
        return http_util.response_with_attachment(request,
                                                  { 'file' : zipped_json_binary, 
                                                    'store_id' : store_id})
    else:
        return http_util.response_with_template(request,
                                                str(__file__), 
                                                'json', 
                                                None, 
                                                { 'json' : json_content})
    
def xml(request): 
    store_id  = request.REQUEST.get('store_id')
    xml_content = None
    zipped_xml_binary = None
    
    store_cache_list = StoreCache.objects.filter(id=store_id)
    
    if len(store_cache_list) == 0:
        cache_obj = cache.update_store_cache(store_id)
    else:
        cache_obj = store_cache_list[0]
        
    xml_content = cache_obj.xml_data
    zipped_xml_binary = binascii.unhexlify(cache_obj.xml_binary_data)
    store_cache_list = None
    cache_obj = None
        
    if request.GET.get('zip', False) == 'true':
        return http_util.response_with_attachment(request,
                                                  { 'file' : zipped_xml_binary, 
                                                    'store_id' : store_id})
    else:
        return http_util.response_with_template(request,
                                                str(__file__), 
                                                'xml', 
                                                None, 
                                                { 'xml' : xml_content})

    
def resource(request):    
    return http_util.redirect_to_url(resource_download_url.get_resource_path(request.REQUEST.get('id'))) 

vims/src/virtualstore/templates/store/add.html
{% extends "shared/master.html" %}

{% block title %}Add Store{% endblock %}

{% block css %}{% endblock %}

{% block script %}
<script>
$(function(){
	  // choose either the full version
	  $("#id_category_attributes").addClass("multiselect").multiselect({sortable: false});
	  $("#id_item_attributes").addClass("multiselect").multiselect({sortable: false});
	  $(".helptext").hide();
	  
	});
</script>
{% endblock %}

{% block body %}

<div class="page">
<div id="menucontainer">           
                <ul id="menu">
                <li><a href="/company/list/">Home</a></li>  
                <li><a href="/game/list/?parent={{view_data.parent_obj.company.id}}">{{view_data.parent_obj.company.name}}</a></li>
                <li><a href="/store/list/?parent={{view_data.parent_obj.id}}">{{view_data.parent_obj.name}}</a></li>
                </ul>
            
            </div>

<div id="main">

{% if form_action == None %}

<form action="/{{view_file}}/{{view_method}}/" method="post">
{% else %}
<form action="{{ form_action }}" method="post">
{% endif %}

<table align="center" border="1">
<tr>
	<th colspan="10">
		<h3>Add Store</h3>		
	</th>
</tr>
{{ form.as_table }}
<tr>
	<td colspan="10" align="center"><input type="submit" value="Submit" /></td>
</tr>
</table>
{% csrf_token %}
<input type="hidden" value="{{view_data.parent_obj.id}}" name="parent" />
{{ form.min_version }}
{{ form.max_version }}
</form>
</div>
</div>
 {% endblock %}

vims/src/virtualstore/templates/store/edit.html
{% extends "shared/master.html" %}

{% block title %}Edit Store{% endblock %}

{% block css %}{% endblock %}

{% block script %}
<script>
$(function(){
	  // choose either the full version
	$("#id_category_attributes").addClass("multiselect").multiselect({sortable: false});
	  $("#id_item_attributes").addClass("multiselect").multiselect({sortable: false});
	  $(".helptext").hide();
	});
</script>
{% endblock %}

{% block body %}

<div class="page">
<div id="menucontainer">           
                <ul id="menu">
                <li><a href="/company/list/">Home</a></li>  
                <li><a href="/game/list/?parent={{view_data.parent_obj.company.id}}">{{view_data.parent_obj.company.name}}</a></li>
                <li><a href="/store/list/?parent={{view_data.parent_obj.id}}">{{view_data.parent_obj.name}}</a></li> 
                </ul>
            
            </div>

<div id="main">

{% if form_action == None %}

<form action="/{{view_file}}/{{view_method}}/" method="post">
{% else %}
<form action="{{ form_action }}" method="post">
{% endif %}

<table align="center" border="1">
<tr>
	<th colspan="10">
		<h3>Edit Store</h3>		
	</th>
</tr>
{{ form.as_table }}
<tr>
	<td colspan="10" align="center"><input type="submit" value="Submit" /></td>
</tr>
</table>
{% csrf_token %}
<input type="hidden" name="id" value="{{ form.instance.id }}" />
<input type="hidden" name="game" value="{{ view_data.parent_obj.id }}" />
{{ form.min_version }}
{{ form.max_version }}
</form>
</div>
</div>
 {% endblock %}

vims/src/virtualstore/templates/store/list.html
{% extends "shared/master.html" %}

{% block title %}Store List{% endblock %}

{% block css %}{% endblock %}

{% block script %}

<script type="text/javascript">

function onDelete(id){

	jConfirm("Are you sure you want to delete ?", "Delete Store", function(result){
				if(result){
					$("#delete_object_id").val(id);
					$("#delete_object_form").submit();
				}
	});
	
}

{% if view_data.message != None %}
	$(document).ready(alert("{{view_data.message}}"));

{% endif %}
</script>
{% endblock %}

{% block body %}
<div class="page">
<div id="menucontainer">           
                <ul id="menu">
                <li><a href="/company/list/">Home</a></li>
                <li><a href="/game/list/?parent={{view_data.parent_obj.company.id}}">{{ view_data.parent_obj.company.name }}</a></li>
                <li><a href="/store/list/?parent={{view_data.parent_obj.id}}">{{ view_data.parent_obj.name }}</a></li>
                </ul>
            
            </div>
<div id="main">
            
<table align="center" width="40%">
<tr>
	<th colspan="13">
		<h3>Store List for {{ view_data.parent_obj.name }}</h3>		
	</th>
</tr>
<tr><td colspan="3"><a href="/{{view_file}}/add/?parent={{view_data.parent_obj.id}}">Add Store</a></td></tr>
<tr>
	<th nowrap>Name</th>
	<th nowrap>&nbsp;</th>
	<th nowrap>&nbsp;</th>
	<th nowrap>&nbsp;</th>
	<th nowrap>&nbsp;</th>
	<th nowrap>&nbsp;</th>
	<th nowrap>&nbsp;</th>
	<th nowrap>Last Pushed</th>
	<th nowrap>Visibe Id</th>
	<th nowrap>Active</th>
	<th nowrap>Position</th>	
<!--
	<th nowrap>Min Version</th>
	<th nowrap>Max Version</th>
-->	
	<th>&nbsp;</th><th>&nbsp;</th>
</tr>
{% ifequal view_data.object_count 0 %}
<tr><td colspan="3"><h3>No Entries</h3></td></tr>
{% else %}

{% for object_in_list in view_data.list_of_object %}
<tr>
	<td nowrap><a href="/category/list/?parent={{ object_in_list.id }}">{{ object_in_list.name }}</a></td>
	<td nowrap><a href="/resource/list/?parent={{ object_in_list.id }}&parent_type=store">Resources</a></td>
	<td nowrap>
	<form action="/store/push/" method="post" id="push_store_form{{ object_in_list.id }}">
	<input type="hidden" name="id" value="{{ object_in_list.id }}" />
	<input type="hidden" name="parent" value="{{view_data.parent_obj.id}}" />
	<a href="javascript:void(0)" onclick="$('#push_store_form{{ object_in_list.id }}').submit()" >Push Store</a>
	{% csrf_token %}
	</form>
	</td>
	<td nowrap><a href="/export/json/?store_id={{ object_in_list.id }}">JSON</a></td>
	<td nowrap><a href="/export/json/?store_id={{ object_in_list.id }}&zip=true">Zipped JSON</a></td>
	<td nowrap><a href="/export/xml/?store_id={{ object_in_list.id }}">XML</a></td>
	<td nowrap><a href="/export/xml/?store_id={{ object_in_list.id }}&zip=true">Zipped XML</a></td>	
	<td nowrap>{{ object_in_list.last_pushed }}</td>
	<td nowrap>{{ object_in_list.visible_id }}</td>
	<td nowrap>{{ object_in_list.is_active }}</td>
	<td nowrap>{{ object_in_list.position }}</td>
<!--
	<td nowrap>{{ object_in_list.min_version }}</td>	
	<td nowrap>{{ object_in_list.max_version }}</td>
-->
	<td nowrap="nowrap" colspan="2"><a href="/{{view_file}}/edit/?id={{object_in_list.id}}&game={{view_data.parent_obj.id}}">EDIT</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" onclick="onDelete('{{object_in_list.id}}')">DELETE</a></td>
	</tr>
{% endfor %}

{% endifequal %}
</table>
</div>
</div>

<form action="/{{view_file}}/delete/" method="post" id="delete_object_form">
<input type="hidden" name="id" id="delete_object_id" />
<input type="hidden" name="game" value="{{view_data.parent_obj.id}}" />
{% csrf_token %}
</form>
 {% endblock %}